using ProjetoNinho.Domain.Conversation;

namespace ProjetoNinho.Application.LLM;

/// <summary>
/// Defines an abstraction for language model completions.
/// </summary>
public interface ILLMProvider
{
    /// <summary>
    /// Generates an assistant response from a composed prompt.
    /// </summary>
    /// <param name="prompt">Prompt text to send to the model.</param>
    /// <param name="cancellationToken">Cancellation token for async flow.</param>
    /// <returns>Assistant response generated by the provider.</returns>
    Task<AssistantResponse> CompleteAsync(
        string prompt, 
        CancellationToken cancellationToken = default);
}