using ProjetoNinho.Domain.Conversation;

namespace ProjetoNinho.Application.LLM;

/// <summary>
/// Defines an abstraction for language model completions.
/// </summary>
public interface ILLMProvider
{
    /// <summary>
    /// Generates an assistant response from structured conversation messages.
    /// </summary>
    /// <param name="messages">Messages to send to the model in chat format.</param>
    /// <param name="cancellationToken">Cancellation token for async flow.</param>
    /// <returns>Assistant response generated by the provider.</returns>
    Task<AssistantResponse> ChatAsync(
        IReadOnlyCollection<Message> messages,
        CancellationToken cancellationToken = default);
}