using System.Net.Http.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Configuration;
using ProjetoNinho.Application.LLM;
using ProjetoNinho.Domain.Conversation;

namespace ProjetoNinho.Infrastructure.LLM;

/// <summary>
/// LLM provider backed by the local Ollama HTTP API.
/// </summary>
public sealed class OllamaProvider : ILLMProvider
{
	private readonly HttpClient _httpClient;
	private readonly IConfiguration _configuration;

	/// <summary>
	/// Initializes a new Ollama provider instance.
	/// </summary>
	/// <param name="httpClient">Configured HTTP client for Ollama requests.</param>
	/// <param name="configuration">Application configuration source.</param>
	public OllamaProvider(HttpClient httpClient, IConfiguration configuration)
	{
		_httpClient = httpClient;
		_configuration = configuration;
	}

	/// <summary>
	/// Sends a prompt to Ollama and returns the generated assistant response.
	/// </summary>
	/// <param name="prompt">Prompt text to send to Ollama.</param>
	/// <param name="cancellationToken">Cancellation token for async flow.</param>
	/// <returns>Assistant response generated by Ollama.</returns>
	public async Task<AssistantResponse> CompleteAsync(
		string prompt,
		CancellationToken cancellationToken = default)
	{
		var model = _configuration["Ollama:Model"] ?? "llama3.2:3b";
		var keepAlive = _configuration["Ollama:KeepAlive"] ?? "30m";
		var maxResponseTokens = int.TryParse(_configuration["Ollama:MaxResponseTokens"], out var parsedMaxTokens)
			? parsedMaxTokens
			: 96;

		var request = new OllamaChatRequest(
			model,
			[
				new OllamaChatRequestMessage("user", prompt)
			],
			Stream: false,
			keepAlive,
			new OllamaChatRequestOptions(maxResponseTokens));

		using var response = await _httpClient.PostAsJsonAsync(
			"api/chat",
			request,
			cancellationToken);

		if (!response.IsSuccessStatusCode)
		{
			var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
			throw new HttpRequestException(
				$"Ollama request failed with status {(int)response.StatusCode}: {errorContent}");
		}

		var ollamaResponse = await response.Content.ReadFromJsonAsync<OllamaChatResponse>(
			cancellationToken: cancellationToken);

		var responseText = ollamaResponse?.Message?.Content ?? ollamaResponse?.Response;

		if (string.IsNullOrWhiteSpace(responseText))
		{
			throw new InvalidOperationException("Ollama returned an empty response.");
		}

		return new AssistantResponse(responseText.Trim());
	}

	private sealed record OllamaChatRequest(
		[property: JsonPropertyName("model")] string Model,
		[property: JsonPropertyName("messages")] IReadOnlyList<OllamaChatRequestMessage> Messages,
		[property: JsonPropertyName("stream")] bool Stream,
		[property: JsonPropertyName("keep_alive")] string KeepAlive = "30m",
		[property: JsonPropertyName("options")] OllamaChatRequestOptions? Options = null);

	private sealed record OllamaChatRequestOptions(
		[property: JsonPropertyName("num_predict")] int NumPredict);

	private sealed record OllamaChatRequestMessage(
		[property: JsonPropertyName("role")] string Role,
		[property: JsonPropertyName("content")] string Content);

	private sealed record OllamaChatMessage(
		[property: JsonPropertyName("role")]
		string? Role,

		[property: JsonPropertyName("content")]
		string? Content);
	private sealed record OllamaChatResponse(
		[property: JsonPropertyName("message")]
		OllamaChatMessage? Message,

		[property: JsonPropertyName("response")]
		string? Response,

		[property: JsonPropertyName("model")]
		string? Model,

		[property: JsonPropertyName("created_at")]
		DateTimeOffset? CreatedAt,

		[property: JsonPropertyName("done")]
		bool Done,

		[property: JsonPropertyName("done_reason")]
		string? DoneReason,

		[property: JsonPropertyName("total_duration")]
		long TotalDuration,

		[property: JsonPropertyName("load_duration")]
		long LoadDuration,

		[property: JsonPropertyName("prompt_eval_count")]
		int PromptEvalCount,

		[property: JsonPropertyName("prompt_eval_duration")]
		long PromptEvalDuration,

		[property: JsonPropertyName("eval_count")]
		int EvalCount,

		[property: JsonPropertyName("eval_duration")]
		long EvalDuration);
}
