using System.Net.Http.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Configuration;
using ProjetoNinho.Application.LLM;
using ProjetoNinho.Domain.Conversation;

namespace ProjetoNinho.Infrastructure.LLM;

/// <summary>
/// LLM provider backed by the local Ollama HTTP API.
/// </summary>
public sealed class OllamaProvider : ILLMProvider
{
	private readonly HttpClient _httpClient;
	private readonly IConfiguration _configuration;

	/// <summary>
	/// Initializes a new Ollama provider instance.
	/// </summary>
	/// <param name="httpClient">Configured HTTP client for Ollama requests.</param>
	/// <param name="configuration">Application configuration source.</param>
	public OllamaProvider(HttpClient httpClient, IConfiguration configuration)
	{
		_httpClient = httpClient;
		_configuration = configuration;
	}

	/// <summary>
	/// Sends a prompt to Ollama and returns the generated assistant response.
	/// </summary>
	/// <param name="prompt">Prompt text to send to Ollama.</param>
	/// <param name="cancellationToken">Cancellation token for async flow.</param>
	/// <returns>Assistant response generated by Ollama.</returns>
	public async Task<AssistantResponse> CompleteAsync(
		string prompt,
		CancellationToken cancellationToken = default)
	{
		var model = _configuration["Ollama:Model"] ?? "llama3.2:3b";

		var request = new OllamaGenerateRequest(
			model,
			prompt,
			Stream: false);

		using var response = await _httpClient.PostAsJsonAsync(
			"api/generate",
			request,
			cancellationToken);

		if (!response.IsSuccessStatusCode)
		{
			var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
			throw new HttpRequestException(
				$"Ollama request failed with status {(int)response.StatusCode}: {errorContent}");
		}

		var ollamaResponse = await response.Content.ReadFromJsonAsync<OllamaGenerateResponse>(
			cancellationToken: cancellationToken);

		if (string.IsNullOrWhiteSpace(ollamaResponse?.Response))
		{
			throw new InvalidOperationException("Ollama returned an empty response.");
		}

		return new AssistantResponse(ollamaResponse.Response.Trim());
	}

	private sealed record OllamaGenerateRequest(
		[property: JsonPropertyName("model")] string Model,
		[property: JsonPropertyName("prompt")] string Prompt,
		[property: JsonPropertyName("stream")] bool Stream);

	private sealed record OllamaGenerateResponse(
		[property: JsonPropertyName("response")] string Response);
}
