using System.Net.Http.Json;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using ProjetoNinho.Application.LLM;
using ProjetoNinho.Domain.Conversation;

namespace ProjetoNinho.Infrastructure.LLM.Ollama;

/// <summary>
/// LLM provider backed by the local Ollama HTTP API.
/// </summary>
public sealed class OllamaProvider : ILLMProvider
{
	private readonly HttpClient _httpClient;
	private readonly ILogger<OllamaProvider> _logger;
	private readonly OllamaOptions _options;

	/// <summary>
	/// Initializes a new Ollama provider instance.
	/// </summary>
	/// <param name="httpClient">Configured HTTP client for Ollama requests.</param>
	/// <param name="logger">Logger used to capture LLM metrics.</param>
	/// <param name="options">Typed Ollama configuration.</param>
	public OllamaProvider(
		HttpClient httpClient,
		ILogger<OllamaProvider> logger,
		IOptions<OllamaOptions> options)
	{
		_httpClient = httpClient;
		_logger = logger;
		_options = options.Value;
	}

	/// <summary>
	/// Sends structured messages to Ollama and returns the generated assistant response.
	/// </summary>
	/// <param name="messages">Structured messages sent to Ollama.</param>
	/// <param name="cancellationToken">Cancellation token for async flow.</param>
	/// <returns>Assistant response generated by Ollama.</returns>
	public async Task<AssistantResponse> ChatAsync(
		IReadOnlyCollection<Message> messages,
		CancellationToken cancellationToken = default)
	{
		var request = OllamaMappings.ToChatRequest(messages, _options);

		using var response = await _httpClient.PostAsJsonAsync(
			"api/chat",
			request,
			cancellationToken);

		if (!response.IsSuccessStatusCode)
		{
			var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
			throw new HttpRequestException(
				$"Ollama request failed with status {(int)response.StatusCode}: {errorContent}");
		}

		var ollamaResponse = await response.Content.ReadFromJsonAsync<OllamaChatResponse>(
			cancellationToken: cancellationToken);

		if (ollamaResponse is null)
		{
			throw new InvalidOperationException("Ollama returned an invalid response payload.");
		}

		var result = OllamaMappings.ToAssistantResponse(ollamaResponse);

		_logger.LogInformation(
			"Ollama respondeu. Modelo: {Model}. Prompt: {PromptTokens}. Resposta: {CompletionTokens}. Tempo: {ElapsedMs} ms",
			result.Model,
			result.PromptTokens,
			result.CompletionTokens,
			result.Duration?.TotalMilliseconds);

		return result;
	}
}