using ProjetoNinho.Application.LLM;
using ProjetoNinho.Domain.Conversation;

namespace ProjetoNinho.Application.Conversation;

/// <summary>
/// Coordinates message composition and LLM chat requests for conversation requests.
/// </summary>
public sealed class ConversationOrchestrator
{
    private readonly PromptCompose _messageComposer;
    private readonly ILLMProvider _llmProvider;
    
    /// <summary>
    /// Initializes a new orchestrator instance.
    /// </summary>
    /// <param name="promptBuilder">Message composition service.</param>
    /// <param name="llmProvider">LLM provider implementation.</param>
    public ConversationOrchestrator(
        PromptCompose promptBuilder, 
        ILLMProvider llmProvider)
    {
        _messageComposer = promptBuilder;
        _llmProvider = llmProvider;
    }

    /// <summary>
    /// Processes a user message and returns the assistant response.
    /// </summary>
    /// <param name="message">User input message.</param>
    /// <param name="cancellationToken">Cancellation token for async flow.</param>
    /// <returns>The assistant response generated by the configured provider.</returns>
    public async Task<AssistantResponse> HandleAsync(
        string message,
        CancellationToken cancellationToken = default)
    {
        var messages = _messageComposer.Build(message);

        return await _llmProvider.ChatAsync(
            messages,
            cancellationToken
        );
    }
}